front_d435i:
  ros__parameters:
    camera_name: front
    publish_tf: false
    enable_infra1: true
    enable_infra2: true
    enable_color: true
    enable_depth: false
    depth_module.emitter_enabled: 0
    depth_module.profile: "640x360x90"
    enable_gyro: true
    enable_accel: true
    gyro_fps: 200
    accel_fps: 200
    unite_imu_method: 2

ydlidar_ros2_driver:
  ros__parameters:
    port: /dev/ydlidar
    frame_id: ydlidar_g4
    ignore_array: ""
    baudrate: 230400
    lidar_type: 1
    device_type: 0
    isSingleChannel: false
    intensity: false
    intensity_bit: 0
    sample_rate: 9
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: false
    inverted: true
    auto_reconnect: true
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 64.0
    range_min: 0.01
    frequency: 10.0
    invalid_range_is_inf: false
    debug: false
